experiment: "overderdamped_k8"
N: 8000           
t_max: 25.0
seed: 42           
k: 8         


defaults: &defaults
  w0: 1.0
  zeta: 0.0
  ic: [0.0, 0.0]  
  forcing: { freq: [1], coef: random }
  mu: [0, 0, 0, 0]


heads:
  - <<: *defaults      # head 1
    ic: [2.0, 0.0]
    zeta: 5

  - <<: *defaults      # head 2
    ic: [1.0, 0.0]
    zeta: 10

  - <<: *defaults      # head 3
    ic: [3.0, 0.0]
    zeta: 20

  - <<: *defaults   # head 4
    ic: [1.0, 0.0]
    zeta: 50

  - <<: *defaults   # head 5
    zeta: 30
    mu: [1, 0, 0, 1]

  - <<: *defaults   # head 6
    zeta: 60
    mu: [1, 0, 0, 1]

  - <<: *defaults  # head 7
    ic: [1.5, 0.0]
    mu: [3, 2, 1, 3]
    zeta: 10

  - <<: *defaults  # head 8
    zeta:  60
    ic: [1.0, 0.0]
    mu: [3, 0, 0, 3]
    forcing: { freq: [5], coef: random }

train:
    'method': equally-spaced-noisy
    'lr': 1e-3
    'num_iter': 15000
    'step_size': 800
    'gamma': 0.96
    'w_ode': 1.5
    'w_ic': 1
    'hidden_layers': [128, 128, 256]
    'use_sine': True
    'use_fourier': False
    'bias': True