experiment: "overdamped_nonlinear"
N: 5120           
t_max: 20.0
seed: 42           
k: 10
epsilon_list: [0.2, 0.3, 0.4, 0.5, 0.2, 0.3, 0.4, 0.5, 0.5, 0.5] 


defaults: &defaults
  w0: 1.0
  zeta: 0.0
  ic: [1.0, 0.0]  
  forcing: { freq: [0], coef: random }
  mu: [0, 0, 0, 0]


heads:
  - <<: *defaults      # head 1
    zeta: 10

  - <<: *defaults      # head 2
    zeta: 20

  - <<: *defaults      # head 3
    zeta: 30

  - <<: *defaults      # head 4
    zeta: 40

  - <<: *defaults     # head 5
    zeta: 10

  - <<: *defaults   # head 6
    zeta: 20

  - <<: *defaults   # head 7
    zeta: 30

  - <<: *defaults   # head 8
    zeta: 40

  - <<: *defaults   # head 9
    zeta: 10

  - <<: *defaults   # head 10
    zeta: 20




train:
    'method': equally-spaced-noisy
    'lr': 1e-3
    'num_iter': 25000
    'step_size': 800
    'gamma': 0.96
    'w_ode': 1.5
    'w_ic': 1
    'hidden_layers': [128, 128, 256]
    'use_sine': False
    'use_fourier': False
    'bias': True