experiment: "overderdamped_k13"
N: 8000           
t_max: 25.0
seed: 42           
k: 15         


defaults: &defaults
  w0: 1.0
  zeta: 0.0
  ic: [0.0, 0.0]  
  forcing: { freq: [1], coef: random }
  mu: [0, 0, 0, 0]


heads:
  - <<: *defaults      # head 1
    ic: [1.0, 0.0]
    zeta: 5
  - <<: *defaults      # head 2
    ic: [1.0, 0.0]
    zeta: 10
  - <<: *defaults      # head 3
    ic: [3.0, 0.0]
    zeta: 20

  - <<: *defaults      # head 4
    ic: [1.0, 0.0]
    zeta: 30

  - <<: *defaults     # head 5
    ic: [2.0, 0.0]
    zeta: 40

  - <<: *defaults   # head 6
    ic: [1.0, 0.0]
    zeta: 50

  - <<: *defaults   # head 7
    zeta: 60
    ic: [2.0, 0.0]

  - <<: *defaults   # head 8
    zeta: 5
    mu: [3, 0, 0, 3]

  - <<: *defaults   # head 9
    zeta: 30
    mu: [3, 0, 0, 3]

  - <<: *defaults   # head 10
    zeta: 60
    mu: [3, 0, 0, 3]
    forcing: { freq: [0], coef: random }

  - <<: *defaults  # head 11
    ic: [1.5, 0.0]
    mu: [3, 2, 1, 3]
    zeta: 10

  - <<: *defaults  # head 11
    ic: [1.5, 0.0]
    mu: [3, 2, 1, 3]
    zeta: 10

  - <<: *defaults   # head 13
    ic: [1.0, 0.0]
    zeta: 30
    mu: [3, 1, 2, 3]
    forcing: { freq: [1, 3], coef: random }


  - <<: *defaults # head 14
    ic: [2.0, 0.0]
    zeta: 40
    mu: [3, 2, 1, 3]
    forcing: { freq: [3, 5], coef: random }

  - <<: *defaults  # head 15
    zeta:  60
    ic: [1.0, 0.0]
    mu: [3, 0, 0, 3]
    forcing: { freq: [3, 5, 8], coef: random }

train:
    'method': equally-spaced-noisy
    'lr': 1e-3
    'num_iter': 40000
    'step_size': 800
    'gamma': 0.96
    'w_ode': 1.5
    'w_ic': 1
    'hidden_layers': [128, 128, 256]
    'use_sine': True
    'use_fourier': False
    'bias': True