experiment: "undamped_k12"
N: 5120           
t_max: 20.0
seed: 42           
k: 12            


defaults: &defaults
  w0: 1.0
  zeta: 0.0
  ic: [0.0, 0.0]  
  forcing: { freq: [], coef: [] }
  mu: 0.0

heads:
  - <<: *defaults
    ic: [1.0, 0.0]
  - <<: *defaults
    ic: [1.5, 0.0]
  - <<: *defaults
    ic: [0.5, 0.0]

  - <<: *defaults
    ic: [1.2, 0.0]
    forcing: { freq: [3], coef: [1.0] }

  - <<: *defaults
    ic: [0.5, 0.0]
    forcing: { freq: [3], coef: [1.0] }

  - <<: *defaults
    ic: [1.0, 0.0]
    forcing: { freq: [6], coef: [1.0] }

  - <<: *defaults
    forcing: { freq: [3, 12], coef: random }

  - <<: *defaults
    forcing: { freq: [2, 4, 5], coef: random }

  - <<: *defaults
    forcing: { freq: [2, 3, 4, 5, 6], coef: random }

  - <<: *defaults
    forcing: { freq: [3, 6, 9, 12, 15], coef: random }

  - <<: *defaults
    forcing: { freq: [6, 9, 18, 21], coef: random }

  - <<: *defaults
    forcing: { freq: [3, 6, 9, 12, 15, 18, 21, 24], coef: random }


train:
    'method': equally-spaced-noisy
    'lr': 1e-3
    'num_iter': 15000
    'step_size': 1000
    'gamma': 0.96
    'w_ode': 1.5
    'w_ic': 1
    'hidden_layers': [256, 256, 512]
    'use_sine': True
    'use_fourier': True
    'n_frequencies': 16
    'scale': 1.0
    'bias': True
