experiment: "underdamped_k6"
N: 5120           
t_max: 20.0
seed: 42           
k: 6        


defaults: &defaults
  w0: 1.0
  zeta: 0.0
  ic: [0.0, 0.0]  
  forcing: { freq: [0], coef: [0] }
  mu: 0.0


heads:
  - <<: *defaults
    ic: [0.5, 0.0]
    zeta: 0.05
  - <<: *defaults
    ic: [1.0, 0.0]
    zeta: 0.1
  - <<: *defaults
    forcing: { freq: [1.0], coef: [1.0] }
    ic: [1.0, 0.0]
    zeta: 0.2

  - <<: *defaults
    ic: [3.0, 0.0]
    forcing: { freq: [1.0], coef: [1.0] }
    zeta: 0.05

  - <<: *defaults
    ic: [1.0, 0.0]
    zeta: 0.1
    forcing: { freq: [1.0], coef: [1.0] }

  - <<: *defaults
    ic: [1.5, 0.0]
    zeta: 0.5
    forcing: { freq: [3.0], coef: [2.0] }

  - <<: *defaults
    zeta: 0.05
    mu: 3
    ic: [0.5, 0.0]
    forcing: { freq: [1.0, 3.0], coef: random }

  - <<: *defaults
    zeta: 0.1
    mu: 3
    forcing: { freq: [1.0, 3.0], coef: random }

  - <<: *defaults
    zeta: 0.3
    mu: 3
    forcing: { freq: [1, 3, 5, 8], coef: random }

  - <<: *defaults
    zeta: 0.05
    mu: 5
    forcing: { freq: [8, 11, 14], coef: random }

  - <<: *defaults
    zeta: 0.2
    mu: 5
    forcing: { freq: [3, 5, 15], coef: random }

  - <<: *defaults
    zeta: 0.1
    mu: 8
    forcing: { freq: [3, 5, 18], coef: random }


train:
    'method': equally-spaced-noisy
    'lr': 1e-3
    'num_iter': 10000
    'step_size': 500
    'gamma': 0.96
    'w_ode': 1.5
    'w_ic': 1
    'hidden_layers': [128, 128, 256]
    'use_sine': True
    'use_fourier': True
    'n_frequencies': 16
    'scale': 1.0
    'bias': True