experiment: "underdamped_nonlinear"
N: 5120           
t_max: 20.0
seed: 42           
k: 10   
epsilon_list: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.3, 0.4, 0.5, 0.6]     


defaults: &defaults
  w0: 1.0
  zeta: 0.0
  ic: [0.0, 0.0]  
  forcing: { freq: [0], coef: [0] }
  mu: 0.0


heads:
  - <<: *defaults
    ic: [0.5, 0.0]
    zeta: 0.1

  - <<: *defaults
    ic: [1.0, 0.0]
    zeta: 0.2

  - <<: *defaults
    ic: [0.5, 0.0]
    zeta: 0.3

  - <<: *defaults
    ic: [1.0, 0.0]
    zeta: 0.4

  - <<: *defaults
    ic: [0.5, 0.0]
    zeta: 0.5

  - <<: *defaults
    ic: [1, 0.0]
    zeta: 0.6

  - <<: *defaults
    zeta: 0.1
    ic: [0.5, 0.0]

  - <<: *defaults
    zeta: 0.2
    ic: [1.0, 0.0]

  - <<: *defaults
    zeta: 0.3
    ic: [1.0, 0.0]

  - <<: *defaults
    zeta: 0.5
    ic: [0.5, 0.0]


train:
    'method': equally-spaced-noisy
    'lr': 1e-3
    'num_iter': 15000
    'step_size': 400
    'gamma': 0.96
    'w_ode': 1.5
    'w_ic': 1
    'hidden_layers': [128, 128, 256]
    'use_sine': True
    'use_fourier': True
    'n_frequencies': 16
    'scale': 1.0
    'bias': True